"""
Surface PDE test: Laplace-Beltrami operator on a surface.

Tests the Laplace-Beltrami equation on a circle (2D curve) and sphere
(3D surface) using the surface quadrature rules generated by algoim.
The Laplace-Beltrami operator is the tangential divergence of the
tangential gradient on a surface.
"""

import pytest
import numpy as np
import dolfinx
import dolfinx.fem
import dolfinx.fem.petsc
import dolfinx.mesh
import ufl
from ufl import inner, grad, dot
from mpi4py import MPI
from petsc4py import PETSc


def _generate_qr(mesh, NN, domain, degree=3):
    """Generate quadrature rules using algoim."""
    import sys
    import os
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "demo"))
    import algoim_utils

    opts = {"verbose": False}
    return algoim_utils.generate_qr(mesh, NN, degree, domain, opts)


def _solve_surface_poisson(domain, N, degree=1, betaN=10.0):
    """Solve a surface Poisson (Laplace-Beltrami) problem.

    Solves -Delta_S u = f on the surface S (circle boundary or sphere
    surface), where Delta_S is the Laplace-Beltrami operator.

    For a unit circle in 2D:
      Surface = {(x,y) : x^2 + y^2 = 1}
      u_exact = cos(theta) = x (first spherical harmonic)
      -Delta_S u = u  => f = x

    For a unit sphere in 3D:
      Surface = {(x,y,z) : x^2 + y^2 + z^2 = 1}
      u_exact = x (first spherical harmonic, eigenvalue 2)
      -Delta_S u = 2*u => f = 2*x

    We use the tangential gradient approach where the surface gradient
    is computed as the projection of the ambient gradient onto the
    surface tangent plane.

    Returns L2 surface error and mesh size h.
    """
    import customquad

    if domain == "circle":
        gdim = 2
        xmin = np.array([-1.11, -1.51])
        xmax = np.array([1.55, 1.22])
        NN = np.array([N, N], dtype=np.int32)
        cell_type = dolfinx.mesh.CellType.quadrilateral
        mesh = dolfinx.mesh.create_rectangle(
            MPI.COMM_WORLD, np.array([xmin, xmax]), NN, cell_type
        )
    elif domain == "sphere":
        gdim = 3
        xmin = np.array([-1.11, -1.51, -1.23])
        xmax = np.array([1.55, 1.22, 1.11])
        NN = np.array([N, N, N], dtype=np.int32)
        cell_type = dolfinx.mesh.CellType.hexahedron
        mesh = dolfinx.mesh.create_box(
            MPI.COMM_WORLD, np.array([xmin, xmax]), NN, cell_type
        )
    else:
        raise ValueError(f"Unknown domain: {domain}")

    result = _generate_qr(mesh, NN, domain)
    [
        cut_cells, uncut_cells, outside_cells,
        qr_pts0, qr_w0, qr_pts_bdry0, qr_w_bdry0, qr_n0,
        xyz, xyz_bdry,
    ] = result

    # For surface PDE, we use boundary quadrature on cut cells
    qr_pts_bdry = [qr_pts_bdry0[k] for k in cut_cells]
    qr_w_bdry = [qr_w_bdry0[k] for k in cut_cells]
    qr_n = [qr_n0[k] for k in cut_cells]

    # Set up tags
    celltags = customquad.utils.get_celltags(
        mesh, cut_cells, uncut_cells, outside_cells,
        uncut_cell_tag=1, cut_cell_tag=2, outside_cell_tag=3,
    )

    # FEM
    V = dolfinx.fem.functionspace(mesh, ("Lagrange", degree))
    u = ufl.TrialFunction(V)
    v = ufl.TestFunction(V)
    x = ufl.SpatialCoordinate(mesh)
    n = ufl.FacetNormal(mesh)
    h = ufl.CellDiameter(mesh)

    # Tangential gradient: grad_S(u) = grad(u) - (n . grad(u)) n
    def grad_t(u, n):
        return grad(u) - dot(n, grad(u)) * n

    # Exact solution: first spherical harmonic u = x[0]
    # For circle: -Delta_S u = u => f = x[0] (eigenvalue 1)
    # For sphere: -Delta_S u = 2*u => f = 2*x[0] (eigenvalue 2)
    if gdim == 2:
        f_ufl = x[0]
        u_exact_ufl = x[0]
        # Mean value on circle (integral of x over unit circle = 0)
        # We need a constraint for uniqueness. Use stabilization.
    else:
        f_ufl = 2 * x[0]
        u_exact_ufl = x[0]

    # Surface bilinear form using tangential gradient
    # a(u,v) = integral_S grad_t(u) . grad_t(v) dS
    # We add a mass term for uniqueness (since constant is in null space)
    # Solve: -Delta_S u + u = f + u_exact
    f_rhs = f_ufl + u_exact_ufl
    a_surf = inner(grad_t(u, n), grad_t(v, n)) + inner(u, v)
    L_surf = inner(f_rhs, v)

    # Surface measure using runtime quadrature
    ds_cut = ufl.dx(
        subdomain_data=celltags,
        metadata={"quadrature_rule": "runtime"},
        domain=mesh,
    )

    qr_bdry = [(cut_cells, qr_pts_bdry, qr_w_bdry, qr_n)]

    # Assemble surface forms
    A = customquad.assemble_matrix(
        dolfinx.fem.form(a_surf * ds_cut(2)), qr_bdry
    )
    A.assemble()

    b = customquad.assemble_vector(
        dolfinx.fem.form(L_surf * ds_cut(2)), qr_bdry
    )

    # Lock inactive DOFs (those not on the surface)
    inactive_dofs = customquad.utils.get_inactive_dofs(V, cut_cells, [])
    A = customquad.utils.lock_inactive_dofs(inactive_dofs, A)

    # Solve
    ksp = PETSc.KSP().create(mesh.comm)
    ksp.setOperators(A)
    ksp.setType("preonly")
    ksp.getPC().setType("lu")
    ksp.getPC().setFactorSolverType("mumps")
    vec = b.copy()
    ksp.solve(b, vec)
    vec.ghostUpdate(addv=PETSc.InsertMode.INSERT, mode=PETSc.ScatterMode.FORWARD)

    uh = dolfinx.fem.Function(V)
    uh.vector.setArray(vec.array)

    # Compute L2 error on surface
    L2_integrand = (uh - u_exact_ufl) ** 2
    L2_err_sq = customquad.assemble_scalar(
        dolfinx.fem.form(L2_integrand * ds_cut(2)), qr_bdry
    )
    L2_err = np.sqrt(abs(L2_err_sq))

    h_val = max(dolfinx.mesh.h(mesh, mesh.topology.dim, cut_cells))

    return L2_err, h_val


@pytest.mark.parametrize("degree", [1, 2])
def test_laplace_beltrami_circle(degree):
    """Test Laplace-Beltrami on circle converges."""
    mesh_sizes = [8, 16, 32]
    h_values = []
    L2_errors = []

    for N in mesh_sizes:
        L2_err, h_val = _solve_surface_poisson("circle", N, degree)
        h_values.append(h_val)
        L2_errors.append(L2_err)

    # Verify convergence (error should decrease)
    for i in range(1, len(L2_errors)):
        assert L2_errors[i] < L2_errors[i - 1], (
            f"L2 error not decreasing: {L2_errors[i]} >= {L2_errors[i-1]}"
        )


@pytest.mark.parametrize("degree", [1, 2])
def test_laplace_beltrami_sphere(degree):
    """Test Laplace-Beltrami on sphere converges."""
    mesh_sizes = [4, 8, 16]
    h_values = []
    L2_errors = []

    for N in mesh_sizes:
        L2_err, h_val = _solve_surface_poisson("sphere", N, degree)
        h_values.append(h_val)
        L2_errors.append(L2_err)

    # Verify convergence
    for i in range(1, len(L2_errors)):
        assert L2_errors[i] < L2_errors[i - 1], (
            f"L2 error not decreasing: {L2_errors[i]} >= {L2_errors[i-1]}"
        )
