"""
Example: Geometry verification for circle and sphere domains.

Computes area, volume, and verifies cut cell classification using
custom quadrature rules generated by algoim.

Usage:
    python geometry_check.py --domain circle --N 16
    python geometry_check.py --domain sphere --N 8
"""

import argparse
import sys
import os
import numpy as np
import dolfinx
import dolfinx.fem
import dolfinx.mesh
import ufl
from mpi4py import MPI

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "demo"))
import algoim_utils
import customquad


def geometry_check(domain, N, verbose=False):
    """Perform geometry checks for the given domain."""

    if domain == "circle":
        gdim = 2
        xmin = np.array([-1.11, -1.51])
        xmax = np.array([1.55, 1.22])
        NN = np.array([N, N], dtype=np.int32)
        cell_type = dolfinx.mesh.CellType.quadrilateral
        mesh = dolfinx.mesh.create_rectangle(
            MPI.COMM_WORLD, np.array([xmin, xmax]), NN, cell_type
        )
        vol_exact = np.pi
        area_exact = 2 * np.pi
    elif domain == "sphere":
        gdim = 3
        xmin = np.array([-1.11, -1.51, -1.23])
        xmax = np.array([1.55, 1.22, 1.11])
        NN = np.array([N, N, N], dtype=np.int32)
        cell_type = dolfinx.mesh.CellType.hexahedron
        mesh = dolfinx.mesh.create_box(
            MPI.COMM_WORLD, np.array([xmin, xmax]), NN, cell_type
        )
        vol_exact = 4 * np.pi / 3
        area_exact = 4 * np.pi
    else:
        raise ValueError(f"Unknown domain: {domain}")

    # Generate quadrature
    opts = {"verbose": verbose}
    result = algoim_utils.generate_qr(mesh, NN, 3, domain, opts)
    [
        cut_cells, uncut_cells, outside_cells,
        qr_pts0, qr_w0, qr_pts_bdry0, qr_w_bdry0, qr_n0,
        xyz, xyz_bdry,
    ] = result

    qr_w = [qr_w0[k] for k in cut_cells]
    qr_w_bdry = [qr_w_bdry0[k] for k in cut_cells]

    # Cell counts
    num_cells = customquad.utils.get_num_cells(mesh)
    print(f"\nCell classification:")
    print(f"  Total cells:   {num_cells}")
    print(f"  Cut cells:     {len(cut_cells)}")
    print(f"  Uncut cells:   {len(uncut_cells)}")
    print(f"  Outside cells: {len(outside_cells)}")
    assert len(cut_cells) + len(uncut_cells) + len(outside_cells) == num_cells

    # Volume
    vol = customquad.utils.volume(xmin, xmax, NN, uncut_cells, qr_w)
    vol_err = abs(vol - vol_exact) / vol_exact
    print(f"\nVolume:")
    print(f"  Computed: {vol:.10f}")
    print(f"  Exact:    {vol_exact:.10f}")
    print(f"  Rel err:  {vol_err:.4e}")

    # Area
    area = customquad.utils.area(xmin, xmax, NN, qr_w_bdry)
    area_err = abs(area - area_exact) / area_exact
    print(f"\nArea (boundary):")
    print(f"  Computed: {area:.10f}")
    print(f"  Exact:    {area_exact:.10f}")
    print(f"  Rel err:  {area_err:.4e}")

    # Cut faces/edges
    tdim = mesh.topology.dim
    mesh.topology.create_connectivity(tdim - 1, tdim)
    face_to_cells = mesh.topology.connectivity(tdim - 1, tdim)
    num_faces = customquad.utils.get_num_faces(mesh)

    cut_set = set(cut_cells)
    cut_boundary_faces = 0
    for f in range(num_faces):
        cells = face_to_cells.links(f)
        if len(cells) == 2:
            c0_cut = cells[0] in cut_set
            c1_cut = cells[1] in cut_set
            if c0_cut != c1_cut:
                cut_boundary_faces += 1

    print(f"\nCut boundary faces: {cut_boundary_faces}")

    if gdim == 3:
        mesh.topology.create_connectivity(1, tdim)
        edge_to_cells = mesh.topology.connectivity(1, tdim)
        num_edges = mesh.topology.index_map(1).size_local

        cut_edges = 0
        for e in range(num_edges):
            cells = edge_to_cells.links(e)
            has_cut = any(c in cut_set for c in cells)
            has_noncut = any(c not in cut_set for c in cells)
            if has_cut and has_noncut:
                cut_edges += 1
        print(f"Cut edges: {cut_edges}")

    # Functional volume check
    qr_pts = [qr_pts0[k] for k in cut_cells]
    celltags = customquad.utils.get_celltags(
        mesh, cut_cells, uncut_cells, outside_cells,
        uncut_cell_tag=1, cut_cell_tag=2, outside_cell_tag=3,
    )
    dx_uncut = ufl.dx(subdomain_data=celltags, domain=mesh)
    dx_cut = ufl.dx(metadata={"quadrature_rule": "runtime"}, domain=mesh)

    vol_uncut = dolfinx.fem.assemble_scalar(
        dolfinx.fem.form(1.0 * dx_uncut(1))
    )
    vol_cut = customquad.assemble_scalar(
        dolfinx.fem.form(1.0 * dx_cut), [(cut_cells, qr_pts, qr_w)]
    )
    vol_func = vol_uncut + vol_cut
    vol_func_err = abs(vol_func - vol_exact) / vol_exact
    print(f"\nFunctional volume:")
    print(f"  Computed: {vol_func:.10f}")
    print(f"  Rel err:  {vol_func_err:.4e}")

    return vol_err, area_err


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Geometry check")
    parser.add_argument("--domain", type=str, default="circle",
                        choices=["circle", "sphere"])
    parser.add_argument("--N", type=int, default=16)
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    print(f"Geometry check for {args.domain} domain with N={args.N}")
    geometry_check(args.domain, args.N, args.verbose)
